
version: '3'

services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: "docker"
      POSTGRES_PASSWORD: "docker"
    ports:
      - "5432:5432"
    volumes:
      - ./src/database/database-docker:/var/lib/postgresql/data 
   